<a href="https://colab.research.google.com/github/Paulo-fernds/Agrupamento/blob/main/AgrupamentoII.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Agrupamento

In [1]:
!pip install plotly --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 15.2 MB 5.7 MB/s 
  Attempting uninstall: plotly
    Found existing installation: plotly 5.5.0
    Uninstalling plotly-5.5.0:
      Successfully uninstalled plotly-5.5.0


In [25]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

# K-means

## Base idade e salário

In [26]:
from sklearn.cluster import KMeans

In [45]:
health_plans = pd.read_csv('/content/plano_saude.csv', header = 0)
health_plans = health_plans.to_numpy()
health_plans


#x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
#y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]  

array([[  18,  871],
       [  23, 1132],
       [  28, 1242],
       [  33, 1356],
       [  38, 1488],
       [  43, 1638],
       [  48, 2130],
       [  53, 2454],
       [  58, 3066],
       [  63, 4090]])

In [48]:
grafico = px.scatter(x = health_plans[:,0], y = health_plans[:,1])
grafico.show()

In [51]:
health_plans = np.array([[  18,  871],
       [  23, 1132],
       [  28, 1242],
       [  33, 1356],
       [  38, 1488],
       [  43, 1638],
       [  48, 2130],
       [  53, 2454],
       [  58, 3066],
       [  63, 4090]])

In [52]:
health_plans

array([[  18,  871],
       [  23, 1132],
       [  28, 1242],
       [  33, 1356],
       [  38, 1488],
       [  43, 1638],
       [  48, 2130],
       [  53, 2454],
       [  58, 3066],
       [  63, 4090]])

In [54]:
scaler_health = StandardScaler()#Padronização de valores
health_plans = scaler_health.fit_transform(health_plans) 

In [55]:
health_plans

array([[-1.5666989 , -1.12704467],
       [-1.21854359, -0.85358678],
       [-0.87038828, -0.73833632],
       [-0.52223297, -0.61889494],
       [-0.17407766, -0.4805944 ],
       [ 0.17407766, -0.32343469],
       [ 0.52223297,  0.19204917],
       [ 0.87038828,  0.53151414],
       [ 1.21854359,  1.17272576],
       [ 1.5666989 ,  2.24560272]])

In [58]:
kmeans_health = KMeans(n_clusters=3)
kmeans_health.fit(health_plans)#Treinamento

KMeans(n_clusters=3)

In [59]:
centroides = kmeans_health.cluster_centers_
centroides

array([[-1.04446594, -0.83446568],
       [ 0.34815531, -0.02011644],
       [ 1.39262125,  1.70916424]])

In [62]:
scaler_health.inverse_transform(kmeans_health.cluster_centers_)

array([[  25.5 , 1150.25],
       [  45.5 , 1927.5 ],
       [  60.5 , 3578.  ]])

In [63]:
rotulos = kmeans_health.labels_
rotulos

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2], dtype=int32)

In [64]:
grafico1 = px.scatter(x = health_plans[:,0], y = health_plans[:,1], color=rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [12, 12, 12])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()

## Dados randômicos

In [66]:
from sklearn.datasets import make_blobs#Gera dados aleatórios

In [67]:
X_random, y_random = make_blobs(n_samples=200, centers=5, random_state=1)

In [68]:
X_random

array([[-1.96576392e+00,  5.23446451e+00],
       [-5.16022348e+00, -7.04217141e+00],
       [-6.17937069e+00, -2.16733539e+00],
       [-7.39138168e+00, -9.49590389e+00],
       [-6.38481234e+00, -8.47302970e+00],
       [-6.26144310e+00, -3.78347905e+00],
       [-2.04278768e+00,  3.07660864e-01],
       [-4.46426086e+00, -4.39451238e+00],
       [-6.40386190e+00, -6.36106990e+00],
       [ 2.42271161e-04,  5.14853403e+00],
       [-5.99212006e+00, -3.91488289e+00],
       [-6.46137477e+00, -3.14560994e+00],
       [-4.10185174e+00, -1.16625450e+00],
       [-1.01341572e+01, -4.07240274e+00],
       [-5.99004766e+00, -2.82631801e+00],
       [-1.14663009e+00,  4.10839703e+00],
       [-1.17104176e+00,  4.33091816e+00],
       [-9.19585147e+00, -3.90678125e+00],
       [-8.30173556e+00, -7.27738918e+00],
       [-7.56309575e+00, -8.46421308e+00],
       [-1.86845414e+00,  4.99311306e+00],
       [-4.22362233e+00, -2.50312346e+00],
       [-1.90838667e+00,  5.86113655e-01],
       [-6.

In [69]:
y_random

array([0, 2, 3, 2, 2, 3, 4, 3, 2, 0, 3, 3, 4, 1, 3, 0, 0, 1, 2, 2, 0, 3,
       4, 3, 4, 1, 2, 4, 4, 1, 2, 4, 0, 3, 2, 0, 1, 2, 1, 4, 2, 1, 4, 4,
       2, 4, 1, 3, 2, 0, 0, 3, 3, 0, 3, 1, 0, 4, 2, 2, 1, 3, 3, 3, 2, 0,
       0, 1, 4, 2, 1, 4, 2, 4, 4, 1, 2, 3, 0, 4, 1, 1, 3, 2, 3, 0, 2, 2,
       2, 1, 4, 3, 0, 4, 3, 1, 4, 0, 2, 1, 0, 2, 4, 1, 4, 2, 1, 2, 3, 0,
       3, 3, 2, 1, 3, 0, 1, 4, 0, 0, 2, 1, 1, 3, 0, 1, 2, 4, 2, 4, 0, 4,
       3, 3, 1, 1, 3, 0, 0, 3, 3, 3, 0, 0, 4, 2, 4, 0, 2, 3, 4, 3, 0, 4,
       3, 1, 1, 1, 0, 2, 4, 0, 1, 0, 4, 1, 1, 1, 3, 4, 1, 4, 4, 3, 0, 2,
       4, 3, 2, 0, 2, 0, 0, 2, 1, 4, 1, 0, 0, 3, 2, 4, 0, 1, 1, 4, 3, 4,
       2, 1])

In [70]:
grafico = px.scatter(x = X_random[:,0], y = X_random[:,1])
grafico.show()

In [71]:
kmeans_blobs = KMeans(n_clusters=5)
kmeans_blobs.fit(X_random)

KMeans(n_clusters=5)

In [72]:
rotulos = kmeans_blobs.predict(X_random)
rotulos

array([0, 1, 2, 1, 1, 2, 4, 2, 1, 0, 2, 2, 2, 3, 2, 0, 0, 3, 1, 1, 0, 2,
       4, 2, 4, 3, 1, 4, 4, 3, 1, 4, 0, 2, 1, 0, 3, 1, 3, 0, 3, 3, 4, 4,
       1, 4, 3, 2, 1, 4, 0, 2, 2, 0, 2, 3, 0, 2, 1, 1, 3, 2, 2, 2, 1, 4,
       0, 3, 4, 1, 3, 4, 1, 4, 4, 3, 1, 3, 0, 4, 3, 3, 2, 1, 2, 0, 1, 1,
       1, 3, 4, 2, 0, 4, 2, 3, 4, 0, 1, 3, 0, 1, 4, 3, 4, 1, 3, 1, 2, 0,
       2, 2, 1, 3, 2, 0, 3, 4, 0, 0, 1, 3, 3, 2, 0, 3, 1, 4, 1, 4, 0, 4,
       2, 2, 3, 3, 2, 0, 0, 2, 2, 2, 0, 0, 4, 1, 4, 0, 1, 2, 4, 2, 0, 4,
       2, 3, 3, 3, 0, 1, 4, 0, 3, 0, 4, 3, 3, 3, 2, 4, 3, 4, 4, 2, 0, 1,
       4, 2, 1, 0, 1, 0, 0, 1, 3, 4, 3, 0, 0, 2, 1, 4, 0, 3, 3, 4, 2, 4,
       1, 3], dtype=int32)

In [73]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[-1.58338528,  4.50520457],
       [-6.87958999, -8.11648104],
       [-5.90368078, -3.04489641],
       [-9.85620522, -3.91021738],
       [-2.17069756,  1.02591979]])

In [74]:
grafico1 = px.scatter(x = X_random[:,0], y = X_random[:,1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [5, 5, 5, 5, 5])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()